### ISSUE TITLE
Substituting formula in a quosure breaks splicing when unquoting

### ISSUE THREAD

**Issue by dpavlic** [hadley/rlang#112]
Hello,

I'm trying to write a simple companion to dplyr's mutate called `mutateX` which would allow me to substitute X for column names in mutate; i.e.,

`mutate(dft, some_var = some_var + 1)` could be written as `mutateX(dft, some_var = X + 1)`.

I'm playing around with the dplyr 0.6.0 RC and rlang to figure out how to go about that. I wrote a quick and dirty implementation that works unless hybrid evaluation is needed, and I'm not sure what the issue is here.

The quick function and my notes:

```
mutateX <- function(.data, ...) {
  modQuos <- rlang::quos(...)
  nonMod <- rlang::quos(...)

  for (qs in seq_along(modQuos)) {
    modQuos[[qs]][[2]] <- do.call(
      'substitute',
      list(modQuos[[qs]][[2]], list(X=as.name(names(modQuos)[[qs]])))
    )
  }
  
  # This will not work:
  dplyr::mutate(.data, !!!modQuos)
  
  # This works, where we just pass nonMod. But why? The objects look the same.
  # dplyr::mutate(.data, !!!nonMod)
}

dft <- data.frame(a = 1:10, b = 101:110)
var <- quo(a)

# This will work
mutate(a, c = (!!var) + 1) 

# This will not.
mutateX(a, c = (!!var) + 1)

# If no unquoting is used, then it _does_ work.
mutateX(a, b = X + 1)
mutateX(a, b = b + 1)
```

**Comment by lionel-** [comment]
`substitute()` works on raw expressions, not on values. A quosure (or an evaluated formula) is a self-quoting expression that is also a value because it has attributes. `substitute()` will only treat the expression that is quoted in the quosure/formula and completely ignore the attributes.

Finally, note that only quosures (a tilde expression + `.Environment` attribute + "quosure" class) will self-evaluate. Your function transforms quosures to raw tilde expressions (e.g. `quote(~foo)`) so they won't self-evaluate.

I would advise against using `substitute()`. See `expr_substitute()` in the dplyr repo (utils-expr.R) for some alternatives. I don't think you'll be able to achieve what you want to achieve (IIUC) in a reliable and tidy way though.

**Comment by dpavlic** [comment]
**Thank you** for a great writeup. It was so confusing to me why these objects, which looked the 'same' would work when no actual !! unqouting took place but not otherwise.

A naive approach indeed suggested the same attributes in both cases:

```
$c
<quosure: global>
~(~a) + 1
```

But, yes, as you suggested, the issue is that substitute stripped out the class of ~a; in other words, `class(nonMod[[1]][[2]][[2]][[2]])` in the example above returns `"quosure" "formula"` whereas the modified version would not. Also appreciate the expr_substitute tip, the initial tests work and things are very promising:

```
mutateX <- function(.data, ...) {
  modQuos <- rlang::quos(...)

  for (qs in seq_along(modQuos)) {
    modQuos[[qs]][[2]] <- dplyr:::expr_substitute(
      modQuos[[qs]][[2]], quote(X), as.name(names(modQuos)[[qs]])
    )
  }
  
  dplyr::mutate(.data, !!!modQuos)
}
```
